'use client';

import { useEffect, useMemo, useState } from 'react';
import { Mail, Phone, Search, Shield, UserRound, RefreshCw, Trash2, Pencil } from 'lucide-react';
import Link from 'next/link';
import { supabase } from '../../../lib/supabaseClient';

function displayName(player) { const nickname = typeof player?.nickname === 'string' ? player.nickname.trim() : ''; return nickname || player?.name || 'Sem nome'; }
function errorMessage(message) { if (message?.includes('ADMIN_ONLY')) return 'Acesso restrito ao administrador.'; if (message?.includes('CANNOT_DELETE_SELF')) return 'Você não pode excluir a própria conta por esta área.'; if (message?.includes('CANNOT_DELETE_ADMIN')) return 'Contas de administrador não podem ser excluídas por esta área.'; if (message?.includes('USER_OWNS_GROUPS')) return 'Este usuário é responsável pela criação de um ou mais grupos. Exclua ou transfira esses grupos antes de excluir o usuário.'; return 'Não foi possível concluir a operação.'; }
export default function AdminPlayersPage() {
 const [players,setPlayers]=useState([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState(null),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');const {data,error:rpcError}=await supabase.rpc('get_admin_players_with_email');if(rpcError){setError(errorMessage(rpcError.message));setPlayers([]);}else setPlayers(data||[]);setLoading(false);};
 useEffect(()=>{load();},[]);
 const remove=async(player)=>{const name=displayName(player);if(!window.confirm(`Excluir o usuário "${name}"?\n\nO acesso à conta será removido e os dados pessoais e registros vinculados ao perfil serão excluídos. Esta operação não pode ser desfeita.`))return;setBusyId(player.id);setError('');const {error:rpcError}=await supabase.rpc('admin_delete_user',{p_user_id:player.id});if(rpcError)setError(errorMessage(rpcError.message));else setPlayers(current=>current.filter(item=>item.id!==player.id));setBusyId(null);};
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return players;return players.filter(p=>[p.name,p.nickname,p.email,p.phone].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));},[players,search]);
 return <main style={{minHeight:'100vh',padding:'24px 16px',background:'#f5f7f5',color:'#132018'}}><div style={{maxWidth:1000,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:20}}><div><div style={{display:'flex',alignItems:'center',gap:8,fontSize:24,fontWeight:800}}><Shield size={22}/> Jogadores</div><div style={{marginTop:5,color:'#607064'}}>Lista administrativa com e-mail, edição e exclusão de contas.</div></div><button onClick={load} disabled={loading} style={S.refresh}><RefreshCw size={15}/> Atualizar</button></div><div style={{position:'relative',marginBottom:14}}><Search size={17} style={{position:'absolute',left:12,top:12,color:'#718078'}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome, apelido ou e-mail" style={S.search}/></div>{error&&<div style={S.error}>{error}</div>}{loading&&<div style={S.loading}>Carregando jogadores...</div>}{!loading&&!error&&<div style={S.table}><div style={S.count}>{filtered.length} jogador(es)</div>{filtered.map(player=><div key={player.id} style={S.row}><div style={S.identity}>{player.avatar_url?<img src={player.avatar_url} alt="" style={S.avatar}/>:<div style={S.fallback}><UserRound size={19}/></div>}<div style={{minWidth:0}}><div style={S.name}>{displayName(player)}</div>{player.nickname&&player.nickname.trim()&&player.name!==displayName(player)&&<div style={S.subname}>{player.name}</div>}</div></div><div style={S.info}><Mail size={16}/><span>{player.email||'E-mail não disponível'}</span></div><div style={S.info}><Phone size={15}/>{player.phone||'Não informado'}{player.is_admin&&<span style={S.admin}>ADMIN</span>}</div><div style={S.actions}><Link href={`/admin/jogadores/${player.id}`} style={S.edit}><Pencil size={15}/> Editar</Link><button onClick={()=>remove(player)} disabled={busyId===player.id||player.is_admin} title={player.is_admin?'Conta administrativa protegida':'Excluir usuário'} style={S.delete}><Trash2 size={15}/>{busyId===player.id?' Excluindo...':' Excluir'}</button></div></div>)}{!filtered.length&&<div style={S.loading}>Nenhum jogador encontrado.</div>}</div>}</div></main>;
}
const S={refresh:{display:'inline-flex',alignItems:'center',gap:7,padding:'9px 12px',border:'1px solid #cbd5ce',borderRadius:10,background:'#fff',cursor:'pointer'},search:{width:'100%',boxSizing:'border-box',padding:'11px 12px 11px 38px',border:'1px solid #cbd5ce',borderRadius:10,background:'#fff',outline:'none'},error:{padding:14,borderRadius:10,background:'#fff0f0',color:'#9b2525',marginBottom:14},loading:{padding:24,textAlign:'center',color:'#607064'},table:{background:'#fff',border:'1px solid #dbe2dc',borderRadius:14,overflow:'hidden'},count:{padding:'12px 16px',borderBottom:'1px solid #e5eae6',color:'#607064',fontSize:13},row:{display:'grid',gridTemplateColumns:'minmax(190px,1.15fr) minmax(200px,1.25fr) minmax(120px,.75fr) auto',gap:12,alignItems:'center',padding:'14px 16px',borderBottom:'1px solid #eef1ee'},identity:{display:'flex',alignItems:'center',gap:10,minWidth:0},avatar:{width:38,height:38,borderRadius:'50%',objectFit:'cover'},fallback:{width:38,height:38,borderRadius:'50%',display:'grid',placeItems:'center',background:'#eef3ef'},name:{fontWeight:700,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'},subname:{color:'#718078',fontSize:12},info:{display:'flex',alignItems:'center',gap:8,minWidth:0,color:'#26362b',fontSize:14,overflow:'hidden'},admin:{marginLeft:'auto',fontSize:11,fontWeight:700,color:'#315c3d'},actions:{display:'flex',alignItems:'center',gap:7},edit:{display:'inline-flex',alignItems:'center',gap:6,padding:'8px 10px',border:'1px solid #cbd5ce',borderRadius:9,background:'#fff',color:'#315c3d',textDecoration:'none',fontWeight:700,fontSize:13},delete:{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6,padding:'8px 10px',border:'1px solid #e1b8b8',borderRadius:9,background:'#fff6f6',color:'#9b2525',cursor:'pointer',fontSize:13}};
