from pathlib import Path
p=Path('app/page.js'); s=p.read_text()

def repl(a,b,marker):
    global s
    if a not in s: raise SystemExit(marker)
    s=s.replace(a,b,1)

repl("function money(n) {\n  return (n || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });\n}\n", "function money(n) {\n  return (n || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });\n}\n\nfunction gameLocationQuery(game) {\n  if (game.locationLatitude != null && game.locationLongitude != null) return `${game.locationLatitude},${game.locationLongitude}`;\n  return [game.local, game.locationAddress, game.locationCity, game.locationState].filter(Boolean).join(', ');\n}\n\nfunction gameMapUrls(game) {\n  const query = gameLocationQuery(game);\n  if (!query) return { google: null, waze: null };\n  const encoded = encodeURIComponent(query);\n  return { google: `https://www.google.com/maps/dir/?api=1&destination=${encoded}`, waze: game.locationLatitude != null && game.locationLongitude != null ? `https://www.waze.com/ul?ll=${encoded}&navigate=yes` : `https://www.waze.com/ul?q=${encoded}&navigate=yes` };\n}\n", 'money marker')
repl("function GameDetail({ game, roster, myId, isAdmin, onBack, onToggleMyRSVP, onSetCost, onSetGkPays, onSetMaxPlayers, onSetGamePixDetails, onDraw, onTogglePaid, onSaveResult, onSaveRatings, onDelete, onShare }) {", "function GameDetail({ game, roster, myId, isAdmin, onBack, onToggleMyRSVP, onSetCost, onSetGkPays, onSetMaxPlayers, onSetGamePixDetails, onSetGameLocation, onDraw, onTogglePaid, onSaveResult, onSaveRatings, onDelete, onShare }) {", 'detail props')
repl("  const [editingMaxPlayers, setEditingMaxPlayers] = useState(false);\n", "  const [editingMaxPlayers, setEditingMaxPlayers] = useState(false);\n  const [editingLocation, setEditingLocation] = useState(false);\n  const [locationNameDraft, setLocationNameDraft] = useState(game.local || '');\n  const [locationAddressDraft, setLocationAddressDraft] = useState(game.locationAddress || '');\n  const [locationCityDraft, setLocationCityDraft] = useState(game.locationCity || '');\n  const [locationStateDraft, setLocationStateDraft] = useState(game.locationState || '');\n  const [locationLatitudeDraft, setLocationLatitudeDraft] = useState(game.locationLatitude ?? '');\n  const [locationLongitudeDraft, setLocationLongitudeDraft] = useState(game.locationLongitude ?? '');\n", 'location state')
repl("  const pixCode = activePixKey\n", "  const mapUrls = gameMapUrls(game);\n  const pixCode = activePixKey\n", 'map urls')
repl("        {canManage && <button className=\"sf-icon-btn sf-danger\" onClick={() => onDelete(game.id)}><Trash2 size={18} /></button>}\n      </div>\n\n      <section className=\"sf-card\">", '''        {canManage && <button className="sf-icon-btn sf-danger" onClick={() => onDelete(game.id)}><Trash2 size={18} /></button>}
      </div>

      <section className="sf-card">
        <div className="sf-card-title"><Target size={16} /> Local da partida</div>
        {!editingLocation ? <>
          <div className="sf-cost-row"><span className="sf-muted">Nome</span><span className="sf-mono-value" style={{ cursor: 'default' }}>{game.local || '—'}</span></div>
          <div className="sf-cost-row"><span className="sf-muted">Endereço</span><span className="sf-mono-value" style={{ cursor: 'default', textAlign: 'right' }}>{game.locationAddress || '—'}</span></div>
          <div className="sf-cost-row"><span className="sf-muted">Cidade/UF</span><span className="sf-mono-value" style={{ cursor: 'default' }}>{game.locationCity || game.locationState ? `${game.locationCity || '—'}/${game.locationState || '—'}` : '—'}</span></div>
          {game.locationLatitude != null && game.locationLongitude != null && <div className="sf-muted-sm" style={{ marginTop: 6 }}>Coordenadas: {game.locationLatitude}, {game.locationLongitude}</div>}
          {(mapUrls.google || mapUrls.waze) && <div className="sf-modal-actions" style={{ marginTop: 10 }}>
            {mapUrls.google && <a className="sf-btn-ghost" href={mapUrls.google} target="_blank" rel="noreferrer">Google Maps</a>}
            {mapUrls.waze && <a className="sf-btn-ghost" href={mapUrls.waze} target="_blank" rel="noreferrer">Waze</a>}
          </div>}
          {canManage && <button className="sf-btn-ghost" style={{ width: '100%', marginTop: 8 }} onClick={() => { setLocationNameDraft(game.local || ''); setLocationAddressDraft(game.locationAddress || ''); setLocationCityDraft(game.locationCity || ''); setLocationStateDraft(game.locationState || ''); setLocationLatitudeDraft(game.locationLatitude ?? ''); setLocationLongitudeDraft(game.locationLongitude ?? ''); setEditingLocation(true); }}>Editar local</button>}
        </> : <>
          <label className="sf-field-label">Nome do local</label><input className="sf-input" value={locationNameDraft} onChange={(e) => setLocationNameDraft(e.target.value)} placeholder="Quadra / arena" />
          <label className="sf-field-label">Endereço</label><input className="sf-input" value={locationAddressDraft} onChange={(e) => setLocationAddressDraft(e.target.value)} placeholder="Rua, número, complemento" />
          <label className="sf-field-label">Cidade</label><input className="sf-input" value={locationCityDraft} onChange={(e) => setLocationCityDraft(e.target.value)} />
          <label className="sf-field-label">Estado/UF</label><input className="sf-input" maxLength="2" value={locationStateDraft} onChange={(e) => setLocationStateDraft(e.target.value.toUpperCase())} />
          <label className="sf-field-label">Latitude (opcional)</label><input type="number" step="any" className="sf-input" value={locationLatitudeDraft} onChange={(e) => setLocationLatitudeDraft(e.target.value)} />
          <label className="sf-field-label">Longitude (opcional)</label><input type="number" step="any" className="sf-input" value={locationLongitudeDraft} onChange={(e) => setLocationLongitudeDraft(e.target.value)} />
          <div className="sf-muted-sm">Geocodificação automática não foi identificada na infraestrutura atual; as coordenadas podem ser informadas manualmente até que um provedor seja definido.</div>
          <div className="sf-modal-actions"><button className="sf-btn-ghost" onClick={() => setEditingLocation(false)}>Cancelar</button><button className="sf-btn-primary" onClick={() => { onSetGameLocation(game.id, { local: locationNameDraft.trim() || null, locationAddress: locationAddressDraft.trim() || null, locationCity: locationCityDraft.trim() || null, locationState: locationStateDraft.trim() || null, locationLatitude: locationLatitudeDraft === '' ? null : Number(locationLatitudeDraft), locationLongitude: locationLongitudeDraft === '' ? null : Number(locationLongitudeDraft) }); setEditingLocation(false); }}>Salvar</button></div>
        </>}
      </section>

      <section className="sf-card">''', 'location section')
repl("  const [newLocal, setNewLocal] = useState('');\n", "  const [newLocal, setNewLocal] = useState('');\n  const [newLocationAddress, setNewLocationAddress] = useState('');\n  const [newLocationCity, setNewLocationCity] = useState('');\n  const [newLocationState, setNewLocationState] = useState('');\n  const [newLocationLatitude, setNewLocationLatitude] = useState('');\n  const [newLocationLongitude, setNewLocationLongitude] = useState('');\n", 'new state')
repl("id: g.id, date: g.date, local: g.local, cost: Number(g.cost) || 0,", "id: g.id, date: g.date, local: g.local, locationAddress: g.location_address || null, locationCity: g.location_city || null, locationState: g.location_state || null, locationLatitude: g.location_latitude != null ? Number(g.location_latitude) : null, locationLongitude: g.location_longitude != null ? Number(g.location_longitude) : null, cost: Number(g.cost) || 0,", 'game map')
repl("  const setMaxPlayers = async (gameId, maxPlayers) => {\n", "  const setGameLocation = async (gameId, { local, locationAddress, locationCity, locationState, locationLatitude, locationLongitude }) => {\n    await supabase.from('games').update({ local: local || null, location_address: locationAddress, location_city: locationCity, location_state: locationState, location_latitude: locationLatitude, location_longitude: locationLongitude }).eq('id', gameId);\n    loadAll();\n  };\n\n  const setMaxPlayers = async (gameId, maxPlayers) => {\n", 'location setter')
repl("date, local: newLocal.trim(), created_by: myId, max_players: maxPlayers, group_id: newGameGroupId || null,", "date, local: newLocal.trim(), location_address: newLocationAddress.trim() || null, location_city: newLocationCity.trim() || null, location_state: newLocationState.trim() || null, location_latitude: newLocationLatitude === '' ? null : Number(newLocationLatitude), location_longitude: newLocationLongitude === '' ? null : Number(newLocationLongitude), created_by: myId, max_players: maxPlayers, group_id: newGameGroupId || null,", 'create payload')
repl("setNewDate(''); setNewLocal(''); setNewMaxPlayers(''); setNewGameGroupId(null);", "setNewDate(''); setNewLocal(''); setNewLocationAddress(''); setNewLocationCity(''); setNewLocationState(''); setNewLocationLatitude(''); setNewLocationLongitude(''); setNewMaxPlayers(''); setNewGameGroupId(null);", 'create reset')
repl("onSetGamePixDetails={setGamePixDetails}\n            onSetMaxPlayers={setMaxPlayers}", "onSetGamePixDetails={setGamePixDetails}\n            onSetGameLocation={setGameLocation}\n            onSetMaxPlayers={setMaxPlayers}", 'detail handler')
repl("<label className=\"sf-field-label\">Local</label>\n            <input className=\"sf-input\" placeholder=\"Quadra / arena\" value={newLocal} onChange={(e) => setNewLocal(e.target.value)} />\n            <label className=\"sf-field-label\">Limite de vagas (opcional)</label>", "<label className=\"sf-field-label\">Nome do local</label>\n            <input className=\"sf-input\" placeholder=\"Quadra / arena\" value={newLocal} onChange={(e) => setNewLocal(e.target.value)} />\n            <label className=\"sf-field-label\">Endereço</label><input className=\"sf-input\" value={newLocationAddress} onChange={(e) => setNewLocationAddress(e.target.value)} placeholder=\"Rua, número, complemento\" />\n            <label className=\"sf-field-label\">Cidade</label><input className=\"sf-input\" value={newLocationCity} onChange={(e) => setNewLocationCity(e.target.value)} />\n            <label className=\"sf-field-label\">Estado/UF</label><input className=\"sf-input\" maxLength=\"2\" value={newLocationState} onChange={(e) => setNewLocationState(e.target.value.toUpperCase())} />\n            <label className=\"sf-field-label\">Latitude (opcional)</label><input type=\"number\" step=\"any\" className=\"sf-input\" value={newLocationLatitude} onChange={(e) => setNewLocationLatitude(e.target.value)} />\n            <label className=\"sf-field-label\">Longitude (opcional)</label><input type=\"number\" step=\"any\" className=\"sf-input\" value={newLocationLongitude} onChange={(e) => setNewLocationLongitude(e.target.value)} />\n            <div className=\"sf-muted-sm\">Geocodificação automática não foi identificada na infraestrutura atual; coordenadas podem ser informadas manualmente.</div>\n            <label className=\"sf-field-label\">Limite de vagas (opcional)</label>", 'new modal')
p.write_text(s)
print('ok')
