-- Preserve every saved team draw for audit/review.
-- The production migration was applied on 2026-09-11; this file reconciles
-- the schema migration source with the production database.

create table if not exists public.game_draw_history (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  draw_number integer not null,
  created_at timestamptz not null default now(),
  created_by uuid not null references public.profiles(id) on delete restrict,
  players_per_team integer not null,
  reserves_per_team integer not null default 0,
  team_a_starters jsonb not null,
  team_b_starters jsonb not null,
  team_a_reserves jsonb not null default '[]'::jsonb,
  team_b_reserves jsonb not null default '[]'::jsonb,
  unique (game_id, draw_number)
);

create index if not exists idx_game_draw_history_game_created
  on public.game_draw_history(game_id, created_at desc);

alter table public.game_draw_history enable row level security;

drop policy if exists game_draw_history_select_participant on public.game_draw_history;
create policy game_draw_history_select_participant
on public.game_draw_history for select to authenticated
using (
  exists (
    select 1 from public.games g
    where g.id = game_draw_history.game_id
      and (
        g.created_by = auth.uid()
        or public.is_group_admin(g.group_id)
        or exists (
          select 1 from public.game_confirmations c
          where c.game_id = g.id and c.user_id = auth.uid()
        )
      )
  )
);

-- set_game_teams is the single write path: it validates the teams, records
-- the next draw number, snapshots the teams, then replaces the live teams.
create or replace function public.set_game_teams(
  p_game_id uuid,
  p_team_a uuid[],
  p_team_b uuid[],
  p_team_a_reserves uuid[] default array[]::uuid[],
  p_team_b_reserves uuid[] default array[]::uuid[]
) returns boolean
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_game public.games%rowtype;
  v_is_admin boolean;
  v_all_ids uuid[];
  v_distinct_count integer;
  v_starter_limit integer;
  v_draw_number integer;
begin
  if auth.uid() is null then raise exception 'Usuário não autenticado'; end if;
  select * into v_game from public.games where id = p_game_id for update;
  if not found then raise exception 'Partida não encontrada'; end if;
  v_is_admin := v_game.group_id is not null and public.is_group_admin(v_game.group_id);
  if not (v_game.created_by = auth.uid() or v_is_admin) then raise exception 'Somente organizador ou administrador pode definir os times'; end if;
  if (v_game.score_a is not null or v_game.score_b is not null) and not v_is_admin then raise exception 'Após o encerramento, somente administradores podem alterar os times'; end if;
  if coalesce(cardinality(p_team_a),0)=0 or coalesce(cardinality(p_team_b),0)=0 then raise exception 'Os dois times precisam ter jogadores'; end if;
  if coalesce(cardinality(p_team_a),0) <> coalesce(cardinality(p_team_b),0) then raise exception 'Os dois times precisam ter o mesmo número de titulares'; end if;
  v_starter_limit := coalesce(v_game.players_per_team, floor(coalesce(v_game.max_players,10)/2.0)::integer);
  if cardinality(p_team_a) > v_starter_limit or cardinality(p_team_b) > v_starter_limit then raise exception 'Quantidade de titulares excede a configuração da partida'; end if;
  if coalesce(cardinality(p_team_a_reserves),0) <> coalesce(cardinality(p_team_b_reserves),0) then raise exception 'Os dois times precisam ter o mesmo número de reservas'; end if;
  if coalesce(cardinality(p_team_a_reserves),0) > coalesce(v_game.reserves_per_team,0) then raise exception 'Quantidade de reservas excede a configuração da partida'; end if;
  v_all_ids := coalesce(p_team_a,array[]::uuid[]) || coalesce(p_team_b,array[]::uuid[]) || coalesce(p_team_a_reserves,array[]::uuid[]) || coalesce(p_team_b_reserves,array[]::uuid[]);
  select count(*) into v_distinct_count from (select distinct unnest(v_all_ids)) x;
  if v_distinct_count <> cardinality(v_all_ids) then raise exception 'Um jogador não pode estar em dois grupos do sorteio'; end if;
  if exists (select 1 from unnest(v_all_ids) as x where not exists (select 1 from public.game_confirmations c where c.game_id=p_game_id and c.user_id=x)) then raise exception 'Todos os jogadores dos times precisam estar confirmados na partida'; end if;
  select coalesce(max(draw_number), 0) + 1 into v_draw_number from public.game_draw_history where game_id = p_game_id;
  insert into public.game_draw_history (game_id, draw_number, created_by, players_per_team, reserves_per_team, team_a_starters, team_b_starters, team_a_reserves, team_b_reserves)
  values (p_game_id, v_draw_number, auth.uid(), coalesce(v_game.players_per_team, v_starter_limit), coalesce(v_game.reserves_per_team, 0), to_jsonb(p_team_a), to_jsonb(p_team_b), to_jsonb(coalesce(p_team_a_reserves,array[]::uuid[])), to_jsonb(coalesce(p_team_b_reserves,array[]::uuid[])));
  delete from public.game_teams where game_id=p_game_id;
  insert into public.game_teams(game_id,user_id,team,role) select p_game_id,x,'A','starter' from unnest(p_team_a) x;
  insert into public.game_teams(game_id,user_id,team,role) select p_game_id,x,'B','starter' from unnest(p_team_b) x;
  insert into public.game_teams(game_id,user_id,team,role) select p_game_id,x,'A','reserve' from unnest(p_team_a_reserves) x;
  insert into public.game_teams(game_id,user_id,team,role) select p_game_id,x,'B','reserve' from unnest(p_team_b_reserves) x;
  return true;
end;
$$;
